#!/usr/bin/env bash

function dotsInstallPackages() {
	echo "🚀 Installing Packages"

	# If no user .local directory, create it and change owner to user
	mkdir -p $HOME/.local/bin && sudo chown $USER:$USER_GROUP $HOME/.local/bin
	echo "💾 Created $HOME/.local/bin"

	# If no user .config directory, create it and change owner to user
	mkdir -p $HOME/.config && sudo chown $USER $HOME/.config
	echo "💾 Created $HOME/.config"

	function install_vim() {
		# Install vim
		if ! command -v vim &>/dev/null; then
			echo "💻 Installing vim"
			sudo apt-get install -y vim
		else
			echo "vim is already installed"
		fi
	}
	install_vim

	function install_lazygit() {
		# Install laygit
		# https://github.com/jesseduffield/lazygit
		if ! command -v lazygit &>/dev/null; then
			echo "⌨️ Installing lazygit"

			LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
			curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
			tar xf lazygit.tar.gz lazygit
			install lazygit -D -t $HOME/.local/bin/
		else
			echo "lazygit is already installed"
		fi
	}
	install_lazygit
	
	function install_lazydocker() {
		# Install lazydocker
		if ! command -v lazydocker &>/dev/null; then
			echo "🐋 Installing lazydocker"

			curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
		else
			echo "lazydocker is already installed"
		fi
	}
	install_lazydocker

	function install_starship() {
		# Install starship prompt
		# https://starship.rs/
		if ! command -v starship &>/dev/null; then
			echo "🚀 Installing starship"
			curl -sS https://starship.rs/install.sh -o ss-install.sh
			sh ss-install.sh --bin-dir $HOME/.local/bin -y
			rm ss-install.sh
		else
			echo "starship is already installed"
		fi
	}
	install_starship

	function install_uv() {
		
		# Install uv, and create a venv for this to run with a specific python version
		# https://astral.sh/uv/
		if ! command -v uv &>/dev/null; then
			echo "🐍 Installing py manager (uv)…"

			curl -LsSf https://astral.sh/uv/install.sh | sh
		else
			echo "py manager (uv) is already installed"
		fi
		UVX_PYTHON_VERSION="3.13"
		
		uv venv --python $UVX_PYTHON_VERSION $HOME/.local/env/devtools

		# alias uvx so that it uses this interpreter always
		echo "alias uvx='uvx --python \$HOME/.local/env/devtools/bin/python'" >> ~/.bash_profile
	}
	install_uv

	echo "✅ Packages have been installed!"
}